In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
from category_encoders import OneHotEncoder
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
import xgboost as xgb
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split, GridSearchCV, KFold, cross_val_score
from sklearn.feature_selection import RFE
from tabulate import tabulate
import json
import numpy as np

# Encode

- Read data

In [2]:
jobs = pd.read_csv("../data/clean data.csv")
jobs.head()

,Salary,Level,Year of Experience,Contract Type,Sex,Programming Language,Language,Location
0,20500000.0,Nhân viên,2 năm,Toàn thời gian,Không yêu cầu,java,tiếng anh,Hà Nội
1,36500000.0,Nhân viên,2 năm,Toàn thời gian,Không yêu cầu,Khác,tiếng anh,Hồ Chí Minh
2,22500000.0,Trưởng/Phó phòng,2 năm,Toàn thời gian,Không yêu cầu,Khác,Không yêu cầu,Hà Nội
3,22500000.0,Trưởng nhóm,3 năm,Toàn thời gian,Không yêu cầu,Khác,Không yêu cầu,Hà Nội
4,30000000.0,Nhân viên,3 năm,Toàn thời gian,Không yêu cầu,php,Không yêu cầu,Hà Nội

- Drop Sex, Contract Type

In [3]:
jobs = jobs.drop(columns = ['Sex', 'Contract Type'])
jobs.head()

,Salary,Level,Year of Experience,Programming Language,Language,Location
0,20500000.0,Nhân viên,2 năm,java,tiếng anh,Hà Nội
1,36500000.0,Nhân viên,2 năm,Khác,tiếng anh,Hồ Chí Minh
2,22500000.0,Trưởng/Phó phòng,2 năm,Khác,Không yêu cầu,Hà Nội
3,22500000.0,Trưởng nhóm,3 năm,Khác,Không yêu cầu,Hà Nội
4,30000000.0,Nhân viên,3 năm,php,Không yêu cầu,Hà Nội

- Categorical encoding for Level variable

In [4]:
jobs['Level'].unique()

array(['Nhân viên', 'Trưởng/Phó phòng', 'Trưởng nhóm', 'Thực tập sinh',
       'Quản lý / Giám sát', 'Giám đốc'], dtype=object)

In [5]:

encoder = OrdinalEncoder(categories=[['Thực tập sinh', 'Nhân viên', 'Trưởng nhóm', 'Trưởng/Phó phòng', 'Quản lý / Giám sát', 'Giám đốc']])
encoded_level = encoder.fit_transform(jobs[['Level']])
jobs['Level'] = encoded_level
jobs.head()

,Salary,Level,Year of Experience,Programming Language,Language,Location
0,20500000.0,1.0,2 năm,java,tiếng anh,Hà Nội
1,36500000.0,1.0,2 năm,Khác,tiếng anh,Hồ Chí Minh
2,22500000.0,3.0,2 năm,Khác,Không yêu cầu,Hà Nội
3,22500000.0,2.0,3 năm,Khác,Không yêu cầu,Hà Nội
4,30000000.0,1.0,3 năm,php,Không yêu cầu,Hà Nội

- Categorical encoding for Year of Experience variable

In [6]:
jobs['Year of Experience'].unique()

array(['2 năm', '3 năm', 'Không yêu cầu kinh nghiệm', '1 năm',
       'Dưới 1 năm', '5 năm', '4 năm', 'Trên 5 năm'], dtype=object)

In [7]:
encoder = OrdinalEncoder(categories=[['Không yêu cầu kinh nghiệm', 'Dưới 1 năm', '1 năm', '2 năm', '3 năm', '4 năm', '5 năm', 'Trên 5 năm']])
encoded_level = encoder.fit_transform(jobs[['Year of Experience']])
jobs['Year of Experience'] = encoded_level
jobs.head()

,Salary,Level,Year of Experience,Programming Language,Language,Location
0,20500000.0,1.0,3.0,java,tiếng anh,Hà Nội
1,36500000.0,1.0,3.0,Khác,tiếng anh,Hồ Chí Minh
2,22500000.0,3.0,3.0,Khác,Không yêu cầu,Hà Nội
3,22500000.0,2.0,4.0,Khác,Không yêu cầu,Hà Nội
4,30000000.0,1.0,4.0,php,Không yêu cầu,Hà Nội

- Categorical encoding for Language variable

In [8]:
one_hot_encoder = OneHotEncoder()
job_pl = one_hot_encoder.fit_transform(jobs['Language'])

jobs = pd.concat([jobs, job_pl], axis=1)
jobs = jobs.drop(columns = ['Language'])
jobs.head()

,Salary,Level,Year of Experience,Programming Language,Location,Language_1,Language_2,Language_3
0,20500000.0,1.0,3.0,java,Hà Nội,1,0,0
1,36500000.0,1.0,3.0,Khác,Hồ Chí Minh,1,0,0
2,22500000.0,3.0,3.0,Khác,Hà Nội,0,1,0
3,22500000.0,2.0,4.0,Khác,Hà Nội,0,1,0
4,30000000.0,1.0,4.0,php,Hà Nội,0,1,0

- Categorical encoding for Location variable

In [9]:
one_hot_encoder = OneHotEncoder()
job_pl = one_hot_encoder.fit_transform(jobs['Location'])

jobs = pd.concat([jobs, job_pl], axis=1)
jobs = jobs.drop(columns = ['Location'])
jobs.head()

,Salary,Level,Year of Experience,Programming Language,Language_1,Language_2,Language_3,Location_1,Location_2,Location_3,Location_4
0,20500000.0,1.0,3.0,java,1,0,0,1,0,0,0
1,36500000.0,1.0,3.0,Khác,1,0,0,0,1,0,0
2,22500000.0,3.0,3.0,Khác,0,1,0,1,0,0,0
3,22500000.0,2.0,4.0,Khác,0,1,0,1,0,0,0
4,30000000.0,1.0,4.0,php,0,1,0,1,0,0,0

- Categorical encoding for Programming Language variable

In [10]:
one_hot_encoder = OneHotEncoder()
job_pl = one_hot_encoder.fit_transform(jobs['Programming Language'])

jobs = pd.concat([jobs, job_pl], axis=1)
jobs = jobs.drop(columns = ['Programming Language'])
jobs

,Salary,Level,Year of Experience,Language_1,Language_2,Language_3,Location_1,Location_2,Location_3,Location_4,...,Programming Language_2,Programming Language_3,Programming Language_4,Programming Language_5,Programming Language_6,Programming Language_7,Programming Language_8,Programming Language_9,Programming Language_10,Programming Language_11
0,20500000.0,1.0,3.0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,36500000.0,1.0,3.0,1,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
2,22500000.0,3.0,3.0,0,1,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,22500000.0,2.0,4.0,0,1,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,30000000.0,1.0,4.0,0,1,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2257,30000000.0,1.0,4.0,1,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2258,11500000.0,1.0,2.0,1,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2259,30000000.0,1.0,3.0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2260,30000000.0,1.0,3.0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2261,30000000.0,1.0,3.0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0

# Correlation with target variable

In [11]:
import pandas as pd

# Tính toán ma trận tương quan
correlation_matrix = jobs.corr()

# Hiển thị tương quan của từng đặc trưng với biến mục tiêu
target_correlation = correlation_matrix['Salary']
print(target_correlation)

Salary                     1.000000
Level                      0.400542
Year of Experience         0.656638
Language_1                -0.060058
Language_2                 0.042468
Language_3                 0.053869
Location_1                 0.021009
Location_2                 0.027226
Location_3                -0.012974
Location_4                -0.084484
Programming Language_1     0.216412
Programming Language_2    -0.342123
Programming Language_3     0.010497
Programming Language_4    -0.082874
Programming Language_5     0.168340
Programming Language_6     0.054714
Programming Language_7     0.101278
Programming Language_8     0.101291
Programming Language_9     0.159216
Programming Language_10    0.093613
Programming Language_11    0.019187
Name: Salary, dtype: float64

- List Models

In [12]:
models = {
    'LinearRegression': LinearRegression(),
    'Ridge': Ridge(),
    'Lasso': Lasso(),
    'GradientBoostingRegressor': GradientBoostingRegressor(),
    'RandomForestRegressor': RandomForestRegressor(),
    'DecisionTreeRegressor': DecisionTreeRegressor(),
    'SVR': SVR(),
    'XGB': xgb.XGBRegressor()
}

In [13]:
X = jobs.drop(columns = ['Salary'])
y = jobs['Salary']

In [14]:
import numpy as np
from sklearn.model_selection import cross_val_score, KFold

# Khởi tạo KFold để kiểm định chéo
kf = KFold(n_splits=5, shuffle=True, random_state=42)

results = []

for name, model in models.items():
    # Đánh giá mô hình sử dụng cross-validation và r2 làm thước đo
    scores = cross_val_score(model, X, y, cv=kf, scoring='r2')
    # Tính R² trung bình
    mean_r2 = np.mean(scores)
    results.append((name, mean_r2))

# Sắp xếp kết quả theo R² Score từ cao xuống thấp
results_df = pd.DataFrame(results, columns=['Model', 'R2 Score']).sort_values(by='R2 Score', ascending=False)

# In kết quả
print(results_df)

# Lấy tên của mô hình có điểm số R² cao nhất
model_best = results_df['Model'].iloc[0]
print("Best performing model:", model_best)

c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.969e+15, tolerance: 1.904e+13
  model = cd_fast.enet_coordinate_descent(
c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.560e+16, tolerance: 1.867e+13
  model = cd_fast.enet_coordinate_descent(
c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.508e+16, tolerance: 1.911e+13
  model = cd_fast.enet_coordinate_descent(
c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.547e+16, tolerance: 1.924e+13
  model = cd_fast.enet_coordinate_descent(
c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.641e+16, tolerance: 1.918e+13
  model = cd_fast.enet_coordinate_descent(

                       Model  R2 Score
4      RandomForestRegressor  0.650821
3  GradientBoostingRegressor  0.647747
7                        XGB  0.639930
5      DecisionTreeRegressor  0.629352
1                      Ridge  0.555075
2                      Lasso  0.554910
0           LinearRegression  0.554490
6                        SVR -0.010912
Best performing model: RandomForestRegressor

# Feature Selection

In [15]:

# Khởi tạo KFold để kiểm định chéo
kf = KFold(n_splits=5, shuffle=True, random_state=42)

results = []
# Định nghĩa mô hình
model = models[model_best]

# Lặp qua số lượng đặc trưng từ 2 đến số lượng đặc trưng tối đa
for i in range(2, len(X.columns) + 1):
    # Thiết lập RFE với số đặc trưng hiện tại
    selector = RFE(model, n_features_to_select=i, step=1)
    selector.fit(X, y)  # Lưu ý là sử dụng toàn bộ dữ liệu X, y
    
    # Đặc trưng được chọn
    selected_features = X.columns[selector.support_]
    
    # Tạo tập dữ liệu chỉ với các đặc trưng được chọn
    X_selected = selector.transform(X)
    
    # Đánh giá mô hình sử dụng cross-validation
    scores = cross_val_score(model, X_selected, y, cv=kf, scoring='r2')
    
    # Tính R² Score trung bình
    mean_r2 = np.mean(scores)
    
    # Lưu kết quả
    results.append((i, selected_features.tolist(), mean_r2))

# Chuyển kết quả vào DataFrame và sắp xếp theo R²
results_df = pd.DataFrame(results, columns=['Num Features', 'Features', 'R2 Score'])
results_df = results_df.sort_values(by='R2 Score', ascending=False)

# In kết quả
print(results_df)

# Lưu các đặc trưng quan trọng nhất từ mô hình tốt nhất
variable_important = results_df.iloc[0, 1]
print("Most important features:", variable_important)

    Num Features                                           Features  R2 Score
8             10  [Level, Year of Experience, Language_1, Langua...  0.658754
12            14  [Level, Year of Experience, Language_1, Langua...  0.655732
9             11  [Level, Year of Experience, Language_1, Langua...  0.655460
10            12  [Level, Year of Experience, Language_1, Langua...  0.654105
7              9  [Level, Year of Experience, Language_1, Langua...  0.653983
13            15  [Level, Year of Experience, Language_1, Langua...  0.653806
11            13  [Level, Year of Experience, Language_1, Langua...  0.653119
6              8  [Level, Year of Experience, Language_2, Locati...  0.652996
14            16  [Level, Year of Experience, Language_1, Langua...  0.652230
15            17  [Level, Year of Experience, Language_1, Langua...  0.651837
17            19  [Level, Year of Experience, Language_1, Langua...  0.651763
5              7  [Level, Year of Experience, Language_2, Locati...  0.651535
18            20  [Level, Year of Experience, Language_1, Langua...  0.651304
16            18  [Level, Year of Experience, Language_1, Langua...  0.650330
4              6  [Level, Year of Experience, Language_2, Locati...  0.632193
3              5  [Level, Year of Experience, Language_2, Progra...  0.625469
2              4  [Level, Year of Experience, Language_2, Progra...  0.596921
1              3  [Level, Year of Experience, Programming Langua...  0.566683
0              2                        [Level, Year of Experience]  0.497842
Most important features: ['Level', 'Year of Experience', 'Language_1', 'Language_2', 'Location_1', 'Location_2', 'Programming Language_1', 'Programming Language_2', 'Programming Language_3', 'Programming Language_4']

# Training

- List Models and Parameter

In [16]:
# Danh sách các mô hình và tham số tương ứng
models = {
    'RandomForestRegressor': (RandomForestRegressor(), {
        'n_estimators': [100, 200, 500],
        'max_depth': [None, 10, 20],
        'min_samples_split': [2, 5, 10],
        'min_samples_leaf': [1, 2, 4],
        'max_features': ['auto', 'sqrt']
    }),
    'XGBRegressor': (xgb.XGBRegressor(), {
        'n_estimators': [100, 200, 500],
        'max_depth': [3, 5, 10],
        'learning_rate': [0.01, 0.1, 0.2],
        'subsample': [0.8, 1.0],
        'colsample_bytree': [0.8, 1.0],
        'gamma': [0, 0.1, 0.2]
    }),
    'GradientBoostingRegressor': (GradientBoostingRegressor(), {
        'n_estimators': [100, 200, 500],
        'max_depth': [3, 5, 10],
        'min_samples_split': [2, 5, 10],
        'min_samples_leaf': [1, 2, 4],
        'max_features': ['auto', 'sqrt'],
        'learning_rate': [0.01, 0.1, 0.2]
    }),
    'DecisionTreeRegressor': (DecisionTreeRegressor(), {
        'max_depth': [None, 10, 20],
        'min_samples_split': [2, 5, 10],
        'min_samples_leaf': [1, 2, 4],
        'max_features': ['auto', 'sqrt']
    }),
    'Ridge': (Ridge(), {
        'alpha': [0.1, 1.0, 10.0]
    }),
    'Lasso': (Lasso(), {
        'alpha': [0.1, 1.0, 10.0]
    }),
    'LinearRegression': (LinearRegression(), {}),
    'SVR': (SVR(), {
        'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
        'C': [0.1, 1.0, 10.0],
        'epsilon': [0.1, 0.2, 0.5],
        'gamma': ['scale', 'auto']
    })
}

In [78]:

# Phân chia tập dữ liệu
X = jobs[variable_important]
y = jobs['Salary']

# Kết quả lưu tham số tốt nhất
best_params = {}

KFold = KFold(n_splits=5, shuffle=True, random_state=42)

# Đào tạo và điều chỉnh mô hình cho từng loại
for model_name, (model, params) in models.items():
    print(f"Training {model_name}...")
    
    # Thiết lập Grid Search với kiểm định chéo
    grid_search = GridSearchCV(estimator=model, param_grid=params, cv=KFold, scoring='neg_mean_squared_error', verbose=1)
    grid_search.fit(X, y)
    
    # Lưu tham số tốt nhất
    best_params[model_name] = grid_search.best_params_
    print(f"Best parameters for {model_name}: {grid_search.best_params_}")

# Ghi kết quả vào file JSON
with open('best_params.json', 'w') as fp:
    json.dump(best_params, fp)

print("All best parameters have been saved to 'best_params.json'.")

Training RandomForestRegressor...
Fitting 5 folds for each of 162 candidates, totalling 810 fits

c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning:
405 fits failed out of a total of 810.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
405 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [            nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan -3.55117019e+13
 -3.55471829e+13 -3.54878406e+13 -3.53879684e+13 -3.54421903e+13
 -3.53861665e+13 -3.54701867e+13 -3.53497020e+13 -3.53992350e+13
 -3.57035707e+13 -3.55902275e+13 -3.55497316e+13 -3.55774311e+13
 -3.56685693e+13 -3.55864450e+13 -3.57400896e+13 -3.57103661e+13
 -3.56914214e+13 -3.66462291e+13 -3.66831438e+13 -3.66459809e+13
 -3.67487038e+13 -3.66807206e+13 -3.67011214e+13 -3.66185022e+13
 -3.66880771e+13 -3.66875649e+13             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan -3.51739551e+13 -3.53760809e+13 -3.53351616e+13
 -3.54932986e+13 -3.53791622e+13 -3.53509075e+13 -3.54900651e+13
 -3.54879545e+13 -3.54005914e+13 -3.55693634e+13 -3.55700212e+13
 -3.55838457e+13 -3.57269202e+13 -3.57198322e+13 -3.56034583e+13
 -3.58617615e+13 -3.57999330e+13 -3.57387790e+13 -3.67615407e+13
 -3.67236491e+13 -3.67251591e+13 -3.67858880e+13 -3.67064475e+13
 -3.67075613e+13 -3.67070801e+13 -3.67147982e+13 -3.66991162e+13
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan -3.55174663e+13
 -3.55358376e+13 -3.54100363e+13 -3.53655223e+13 -3.53062098e+13
 -3.53529277e+13 -3.54872083e+13 -3.54569252e+13 -3.53440163e+13
 -3.55798472e+13 -3.55690867e+13 -3.55995781e+13 -3.58490852e+13
 -3.56092911e+13 -3.55520255e+13 -3.56307365e+13 -3.57385042e+13
 -3.55933615e+13 -3.67672976e+13 -3.66565817e+13 -3.65755859e+13
 -3.66004768e+13 -3.67770230e+13 -3.66352197e+13 -3.67251441e+13
 -3.67576531e+13 -3.66751729e+13]
  warnings.warn(

Best parameters for RandomForestRegressor: {'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100}
Training XGBRegressor...
Fitting 5 folds for each of 324 candidates, totalling 1620 fits
Best parameters for XGBRegressor: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100, 'subsample': 0.8}
Training GradientBoostingRegressor...
Fitting 5 folds for each of 486 candidates, totalling 2430 fits

c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning:
1215 fits failed out of a total of 2430.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1215 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of GradientBoostingRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [            nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan -6.11551111e+13
 -4.70294667e+13 -3.93938866e+13 -6.09633183e+13 -4.74199536e+13
 -3.94251900e+13 -6.10555033e+13 -4.72605459e+13 -3.93772196e+13
 -6.05717198e+13 -4.72525657e+13 -3.94787672e+13 -6.08314560e+13
 -4.71684312e+13 -3.95283571e+13 -6.14693652e+13 -4.73330822e+13
 -3.93700661e+13 -6.11236719e+13 -4.72372151e+13 -3.93063584e+13
 -6.05744256e+13 -4.73617971e+13 -3.95853778e+13 -6.11067137e+13
 -4.73471368e+13 -3.94622191e+13             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan -5.15778723e+13 -3.98292251e+13 -3.54271261e+13
 -5.15543565e+13 -3.98071544e+13 -3.54875774e+13 -5.17210118e+13
 -3.97753198e+13 -3.54388878e+13 -5.14887354e+13 -4.00320054e+13
 -3.55244750e+13 -5.17201454e+13 -3.98462611e+13 -3.55446743e+13
 -5.16012468e+13 -3.97846108e+13 -3.55993630e+13 -5.20574326e+13
 -4.02801344e+13 -3.58972888e+13 -5.18258285e+13 -4.01772556e+13
 -3.58932392e+13 -5.19509315e+13 -4.00986583e+13 -3.58831699e+13
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan -4.42189387e+13
 -3.64971015e+13 -3.59584551e+13 -4.42197319e+13 -3.62960529e+13
 -3.58699558e+13 -4.43726758e+13 -3.63194285e+13 -3.55958104e+13
 -4.47625869e+13 -3.64521120e+13 -3.54588961e+13 -4.47627597e+13
 -3.64315319e+13 -3.54765854e+13 -4.49274486e+13 -3.64668871e+13
 -3.53991223e+13 -4.58002175e+13 -3.68248414e+13 -3.52326339e+13
 -4.57974202e+13 -3.67902256e+13 -3.52322882e+13 -4.58310797e+13
 -3.68664994e+13 -3.52178878e+13             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan -3.69476046e+13 -3.61050035e+13 -3.55158461e+13
 -3.71957762e+13 -3.59844461e+13 -3.55454237e+13 -3.74469475e+13
 -3.60473421e+13 -3.55209682e+13 -3.75224208e+13 -3.58388739e+13
 -3.58566591e+13 -3.72895892e+13 -3.57064454e+13 -3.56098154e+13
 -3.73212789e+13 -3.60683825e+13 -3.56541718e+13 -3.76823736e+13
 -3.61390202e+13 -3.55167194e+13 -3.71376889e+13 -3.63505693e+13
 -3.56462193e+13 -3.79615664e+13 -3.60671720e+13 -3.54941076e+13
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan -3.54835756e+13
 -3.57111592e+13 -3.62366287e+13 -3.53822486e+13 -3.58432518e+13
 -3.62946184e+13 -3.52711991e+13 -3.55334881e+13 -3.60614758e+13
 -3.53031751e+13 -3.53288806e+13 -3.60021014e+13 -3.52097958e+13
 -3.54586319e+13 -3.61771118e+13 -3.53517591e+13 -3.51305689e+13
 -3.58063903e+13 -3.54601237e+13 -3.53968874e+13 -3.58908419e+13
 -3.52896103e+13 -3.55135540e+13 -3.57904166e+13 -3.54463350e+13
 -3.55303953e+13 -3.58729481e+13             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan -3.63393386e+13 -3.60737756e+13 -3.61664233e+13
 -3.63259097e+13 -3.61892183e+13 -3.60794276e+13 -3.58609826e+13
 -3.59305584e+13 -3.58990296e+13 -3.57080937e+13 -3.59551162e+13
 -3.62186282e+13 -3.57648136e+13 -3.60600610e+13 -3.61435749e+13
 -3.56358226e+13 -3.58812481e+13 -3.61126306e+13 -3.54852687e+13
 -3.56431074e+13 -3.60861057e+13 -3.53833358e+13 -3.57577663e+13
 -3.60987406e+13 -3.54062399e+13 -3.55825347e+13 -3.58911732e+13
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan -3.60622439e+13
 -3.58666338e+13 -3.59814032e+13 -3.61569663e+13 -3.57703530e+13
 -3.59619423e+13 -3.62803043e+13 -3.57869402e+13 -3.57856692e+13
 -3.60321929e+13 -3.60318196e+13 -3.60676876e+13 -3.59623397e+13
 -3.56762350e+13 -3.57643701e+13 -3.61066234e+13 -3.55139581e+13
 -3.57274036e+13 -3.64590080e+13 -3.56562908e+13 -3.56668542e+13
 -3.60813716e+13 -3.58517284e+13 -3.57540711e+13 -3.61820560e+13
 -3.56258694e+13 -3.55947830e+13             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan -3.58553255e+13 -3.63629731e+13 -3.66700832e+13
 -3.57749696e+13 -3.61990264e+13 -3.68259626e+13 -3.54216402e+13
 -3.61692410e+13 -3.66526440e+13 -3.55932226e+13 -3.59548659e+13
 -3.64700757e+13 -3.59356161e+13 -3.61587357e+13 -3.66782344e+13
 -3.55072526e+13 -3.58229519e+13 -3.66577362e+13 -3.53626425e+13
 -3.58217507e+13 -3.62452924e+13 -3.54630415e+13 -3.57365387e+13
 -3.62921053e+13 -3.56606055e+13 -3.57000966e+13 -3.62672304e+13
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan -3.61710171e+13
 -3.61325027e+13 -3.65228483e+13 -3.61661406e+13 -3.62965447e+13
 -3.60197520e+13 -3.63952171e+13 -3.61354602e+13 -3.62946537e+13
 -3.61442649e+13 -3.64071125e+13 -3.63655578e+13 -3.60217623e+13
 -3.62103689e+13 -3.65796950e+13 -3.60562087e+13 -3.61207333e+13
 -3.61929021e+13 -3.58482608e+13 -3.59992440e+13 -3.64904884e+13
 -3.56771297e+13 -3.58324263e+13 -3.64166712e+13 -3.57594547e+13
 -3.61626610e+13 -3.62422977e+13]
  warnings.warn(

Best parameters for GradientBoostingRegressor: {'learning_rate': 0.1, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 10, 'n_estimators': 200}
Training DecisionTreeRegressor...
Fitting 5 folds for each of 54 candidates, totalling 270 fits

c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning:
135 fits failed out of a total of 270.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
135 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [            nan             nan             nan             nan
             nan             nan             nan             nan
             nan -3.73411852e+13 -3.77463227e+13 -3.78368880e+13
 -3.97693021e+13 -3.75783250e+13 -3.79403798e+13 -4.03866393e+13
 -4.09816856e+13 -4.02923414e+13             nan             nan
             nan             nan             nan             nan
             nan             nan             nan -3.73342522e+13
 -3.89101283e+13 -3.85350910e+13 -3.80980840e+13 -3.97626619e+13
 -3.96712696e+13 -4.04249952e+13 -4.15870013e+13 -4.02126416e+13
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan -3.81841549e+13 -3.71950564e+13 -3.70263482e+13
 -3.73076398e+13 -3.86588361e+13 -3.80179533e+13 -4.09357934e+13
 -3.89469092e+13 -3.91482503e+13]
  warnings.warn(

Best parameters for DecisionTreeRegressor: {'max_depth': 20, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 10}
Training Ridge...
Fitting 5 folds for each of 3 candidates, totalling 15 fits
Best parameters for Ridge: {'alpha': 1.0}
Training Lasso...
Fitting 5 folds for each of 3 candidates, totalling 15 fits
Best parameters for Lasso: {'alpha': 10.0}
Training LinearRegression...
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Best parameters for LinearRegression: {}
Training SVR...
Fitting 5 folds for each of 72 candidates, totalling 360 fits
Best parameters for SVR: {'C': 10.0, 'epsilon': 0.5, 'gamma': 'scale', 'kernel': 'poly'}
All best parameters have been saved to 'best_params.json'.

In [39]:
from sklearn.model_selection import KFold
# Đọc file JSON
with open('best_params.json', 'r') as fp:
    best_params = json.load(fp)

# Tạo dictionary của các mô hình đã cấu hình với random_state
models_configured = {
    'RandomForestRegressor': RandomForestRegressor(random_state=42, **best_params['RandomForestRegressor']),
    'XGBRegressor': xgb.XGBRegressor(random_state=42, **best_params['XGBRegressor']),
    'GradientBoostingRegressor': GradientBoostingRegressor(random_state=42, **best_params['GradientBoostingRegressor']),
    'DecisionTreeRegressor': DecisionTreeRegressor(random_state=42, **best_params['DecisionTreeRegressor']),
    'Ridge': Ridge(random_state=42, **best_params['Ridge']),
    'Lasso': Lasso(random_state=42, **best_params['Lasso']),
    'LinearRegression': LinearRegression(**best_params['LinearRegression']),
    'SVR': SVR(**best_params['SVR'])
}


# Khởi tạo KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Đánh giá mỗi mô hình sử dụng cross-validation và lưu kết quả
results = {}
for name, model in models_configured.items():
    scores = cross_val_score(model, X, y, cv=kf, scoring='r2')
    results[name] = np.mean(scores)

# Sắp xếp kết quả theo R2 Score giảm dần và in ra
sorted_results = sorted(results.items(), key=lambda x: x[1], reverse=True)
for model_name, score in sorted_results:
    print(f"{model_name}: R2 Score = {score}")

c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.969e+15, tolerance: 1.904e+13
  model = cd_fast.enet_coordinate_descent(
c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.560e+16, tolerance: 1.867e+13
  model = cd_fast.enet_coordinate_descent(
c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.508e+16, tolerance: 1.911e+13
  model = cd_fast.enet_coordinate_descent(
c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.548e+16, tolerance: 1.924e+13
  model = cd_fast.enet_coordinate_descent(
c:\Users\Mai Xuan Truong\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.641e+16, tolerance: 1.918e+13
  model = cd_fast.enet_coordinate_descent(

XGBRegressor: R2 Score = 0.6593867095909736
GradientBoostingRegressor: R2 Score = 0.6592706950769202
RandomForestRegressor: R2 Score = 0.6541111740961283
DecisionTreeRegressor: R2 Score = 0.6234154590458251
Ridge: R2 Score = 0.5550747244665604
Lasso: R2 Score = 0.5549118730981188
LinearRegression: R2 Score = 0.5544898469329764
SVR: R2 Score = -0.007950186934503733